//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWorldPizza.WSWorldPizza {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SomeError", Namespace="http://schemas.datacontract.org/2004/07/WSWorldPizza.Models")]
    [System.SerializableAttribute()]
    public partial class SomeError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSWorldPizza.IServiceWorldPizza")]
    public interface IServiceWorldPizza {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWorldPizza/bienvenida", ReplyAction="http://tempuri.org/IServiceWorldPizza/bienvenidaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebWorldPizza.WSWorldPizza.SomeError), Action="http://tempuri.org/IServiceWorldPizza/bienvenidaSomeErrorFault", Name="SomeError", Namespace="http://schemas.datacontract.org/2004/07/WSWorldPizza.Models")]
        string bienvenida();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWorldPizza/bienvenida", ReplyAction="http://tempuri.org/IServiceWorldPizza/bienvenidaResponse")]
        System.Threading.Tasks.Task<string> bienvenidaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWorldPizzaChannel : WebWorldPizza.WSWorldPizza.IServiceWorldPizza, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWorldPizzaClient : System.ServiceModel.ClientBase<WebWorldPizza.WSWorldPizza.IServiceWorldPizza>, WebWorldPizza.WSWorldPizza.IServiceWorldPizza {
        
        public ServiceWorldPizzaClient() {
        }
        
        public ServiceWorldPizzaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWorldPizzaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWorldPizzaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWorldPizzaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string bienvenida() {
            return base.Channel.bienvenida();
        }
        
        public System.Threading.Tasks.Task<string> bienvenidaAsync() {
            return base.Channel.bienvenidaAsync();
        }
    }
}
